django/My_ManyToOne/My_ManyToOne/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

django/My_ManyToOne/accounts/urls.py
from django.urls import path
from . import views
app_name='accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.change_password, name='change_password'),
]

django/My_ManyToOne/articles/urls.py
from django.urls import path
from . import views
app_name='articles'
urlpatterns = [
    path('',views.index,name='index'),
    path('create/',views.create, name='create'),
    path('update/<int:pk>/',views.update, name='update'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('delete/<int:pk>/',views.delete, name='delete'),
    path('<int:article_pk>/comments/',views.comment_create,name='comment_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/',views.comment_delete,name='comment_delete'),
]

django/My_ManyToOne/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    pass

django/My_ManyToOne/articles/models.py
from django.db import models
from django.conf import settings
# Create your models here.
class Article(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE, related_name='articles')
    title=models.CharField(max_length=50)
    content=models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    modified_at=models.DateTimeField(auto_now=True)


class Comment(models.Model):
    article=models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='comments')
    content=models.CharField(max_length=200)
    create_at=models.DateTimeField(auto_now_add=True)
    modified_at=models.DateTimeField(auto_now=True)

django/My_ManyToOne/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm,UserCreationForm
from django.contrib.auth import get_user_model
class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model=get_user_model()
        fields=UserCreationForm.Meta.fields + ('email',)


class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm.Meta):
        model=get_user_model()
        fields=('email','first_name','last_name',)

django/My_ManyToOne/articles/forms.py
from django import forms
from .models import Article,Comment

class ArticleForm(forms.ModelForm):

    class Meta:
        model=Article
        fields=['title','content',]

class CommentForm(forms.ModelForm):
    
    class Meta:
        model=Comment
        exclude=['article','user',]

django/My_ManyToOne/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.views.decorators.http import require_POST,require_http_methods
from django.contrib.auth.decorators import login_required
from .forms import CustomUserChangeForm,CustomUserCreationForm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash

# Create your views here.
@require_http_methods(['GET','POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    if request.method=='POST':
        form=CustomUserCreationForm(request.POST)
        if form.is_valid():
            user=form.save()
            auth_login(request,user)
            return redirect('articles:index')
    else:
        form=CustomUserCreationForm()
    context={
        'form':form,
    }
    return render(request,'accounts/signup.html', context)


@login_required
@require_http_methods(['GET','POST'])
def update(request):
    if request.method=='POST':
        form=CustomUserChangeForm(request.POST,instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:update')
    else:
        form=CustomUserChangeForm(instance=request.user)
    context={
        'form':form,
    }
    return render(request,'accounts/update.html', context)


@require_http_methods(['GET','POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    if request.method=='POST':
        form=AuthenticationForm(request,request.POST)
        if form.is_valid(): 
            auth_login(request,form.get_user())
            return redirect(request.GET.get('next') or 'articles:index')
    else:
        form=AuthenticationForm()
    context={
        'form':form,
    }
    return render(request, 'accounts/login.html', context)


@require_POST
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('articles:index')

@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
    return redirect('articles:index')
    

@login_required
@require_http_methods(['GET','POST'])
def change_password(request):
    if request.method=='POST':
        form=PasswordChangeForm(request.user,request.POST)
        if form.is_valid():
            user=form.save()
            update_session_auth_hash(request,user)
            return redirect('articles:index')
    else:
        form=PasswordChangeForm(request.user)
    context={
        'form':form,
    }
    return render(request,'accounts/change_password.html', context)

django/My_ManyToOne/articles/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.decorators.http import require_http_methods,require_POST
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    articles=Article.objects.order_by('-pk')
    context={
        'articles':articles
    }
    return render(request,'articles/index.html', context)

@login_required
@require_http_methods(['GET','POST'])
def create(request):
    if request.method=='POST':
        form=ArticleForm(request.POST)
        if form.is_valid():
            article=form.save(commit=False)
            article.user=request.user
            article.save()
            return redirect('articles:detail', article.pk)
    else:
        form=ArticleForm()
    context={
        'form':form,
    }
    return render(request,'articles/create.html',context)


def detail(request,pk):
    article=Article.objects.get(pk=pk)
    form=CommentForm()
    context={
        'article':article,
        'form':form,
    }
    return render(request,'articles/detail.html',context)

@require_http_methods(['GET','POST'])
def update(request,pk):
    article=get_object_or_404(Article,pk=pk)
    if request.user==article.user:
        if request.method=='POST':
            form=ArticleForm(request.POST,instance=article)
            if form.is_valid():
                form.save()
                return redirect('articles:detail', article.pk)
        else:
            form=ArticleForm(instance=article)
        context={
            'form':form,
        }
        return render(request, 'articles/create.html',context)
    return redirect('articles:detail',article.pk)


@require_POST
def delete(request,pk):
    article=Article.objects.get(pk=pk)
    if request.user==article.user:
        article.delete()
    return redirect('articles:index')


@require_POST
def comment_create(request,article_pk):
    if request.user.is_authenticated:
        article=get_object_or_404(Article,pk=article_pk)
        comment_form=CommentForm(request.POST)
        if comment_form.is_valid():
            comment=comment_form.save(commit=False)
            comment.article=article
            comment.user=request.user
            comment_form.save()
            return redirect('articles:detail',article.pk)
        context={
            'article':article,
            'comment_form':comment_form,
        }
        return render(request,'articles/detail.html', context)
    return redirect('accounts:login')



@require_POST
def comment_delete(request,article_pk,comment_pk):
    comment=get_object_or_404(Comment,pk=comment_pk)
    if request.user==comment.user:
        comment.delete()
    return redirect('articles:detail', article_pk)

django/My_ManyToOne/My_ManyToOne/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>My_ManyToOne</title>
  </head>
  <body>
    {% if request.user.is_authenticated %}
      <form action="{% url 'accounts:logout' %}" method='POST'>
        {% csrf_token %}
        <button>로그아웃</button>
      </form>
      <a href="{% url 'accounts:update' %}">회원정보수정</a>
      <form action="{% url 'accounts:delete' %}" method='POST'>
        {% csrf_token %}
        <button>회원탈퇴</button>
      </form>
    {% else %}
      <a href="{% url 'accounts:signup' %}">회원가입</a>
      <a href="{% url 'accounts:login' %}">로그인</a>
    {% endif %}
    <a href="{% url 'articles:index' %}">Article</a>
    <a href="{% url 'articles:create' %}">Create</a>
    {% block content %}
    {% endblock  %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

django/My_ManyToOne/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% block content %}
<h1>비밀번호변경</h1>
<form action="" method='POST'>
    {% csrf_token %}
    {{form.as_p}}
    <button>변경하기</button>
</form>
{% endblock  %}

django/My_ManyToOne/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<h1>로그인</h1>
<form action="" method='POST'>
    {% csrf_token %}
    {{form.as_p}}
    <button>로그인하기</button>
</form>
{% endblock  %}

django/My_ManyToOne/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% block content %}
<h1>회원정보수정</h1>
<form action="" method='POST'>
    {% csrf_token %}
    {{form.as_p}}
    <button>정보수정</button>
</form>
{% endblock  %}

django/My_ManyToOne/articles/templates/articles/create.html
{% extends 'base.html' %}
{% block content %}
<h1>게시글 생성</h1>
<form action="" method='POST'>
    {% csrf_token %}
    {{form.as_p}}
    <button>생성하기</button>
</form>
{% endblock  %}

django/My_ManyToOne/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% block content %}
<h1>상세페이지</h1>
<h3>TITLE : {{article.title}}</h3>
<p>CONTENT : {{article.content}}</p>
<p>CREATED_AT : {{article.created_at}}</p>
<p>MODIFIED_AT : {{article.modified_at}}</p>
<a href="{% url 'articles:index' %}">[BACK]</a>
<a href="{% url 'articles:update' article.pk %}">정보수정</a>
<form action="{% url 'articles:delete' article.pk %}" method='POST'>
    {% csrf_token %}
    <button>삭제하기</button>
</form>
<h3>댓글목록</h3>
<form action="{% url 'articles:comment_create' article.pk%}" method='POST' >
    {% csrf_token %}
    {{form.as_p}}
    <button class="btn btn-primary d-inline">댓글생성</button>
</form>
{% for comment in article.comments.all %}
    <li>
        <p><b>{{comment.user}} - {{comment.content}}</b></p>
        {% if request.user == comment.user %}
            <form action="{% url 'articles:comment_delete' article.pk comment.pk %}" method='POST' class="d-inline">
                {% csrf_token %}
                <button class="btn btn-primary">삭제</button>
            </form>
        {% endif %}
    </li>
{% endfor %}
{% endblock  %}

django/My_ManyToOne/articles/templates/articles/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Article</h1>
{% for article in articles %}
<h3><a href="{% url 'articles:detail' article.pk %}">{{article.title}}</a></h3>
{% endfor %}
{% endblock  %}